# Generated by Django 4.2.5 on 2025-05-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_adress_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom',
        ),
    ]
